Repository OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa, pull requests merged in 2024-11, with the labels that each got.

#124 Frontend addition of a title and a footer
  fullstack/public/images/github-mark-white.png
  fullstack/src/app/page.js
  fullstack/src/components/Footer/Footer.css
  fullstack/src/components/Footer/Footer.jsx
  fullstack/src/components/footer.jsx
  fullstack/src/components/header.jsx
Labels: enhancement, frontend

#127 126 add rain calculation
  fullstack/src/app/api/get-data/route.js
  fullstack/src/app/api/get-graph-data/route.js
  fullstack/src/app/api/rain-data/route.js
Labels: database, backend

#136 Resolve issue #128. Multiplied the wind speed into km/h
  fullstack/src/components/widget.jsx
  sensors/i2c_master_slave/mega_slave/mega_slave.ino
Labels: bug, frontend, backend

#133 Graphs displaying data dynamically in widgets
  fullstack/README.md
  fullstack/package-lock.json
  fullstack/package.json
  fullstack/src/app/api/rain-data/route.js
  fullstack/src/app/page.css
  fullstack/src/app/page.js
  fullstack/src/app/utils/chartUtils.js
  fullstack/src/components/WidgetBase.css
  fullstack/src/components/graphs/BarChartComponent.jsx
  fullstack/src/components/graphs/LineChartComponent.jsx
  fullstack/src/components/widget.css
  fullstack/src/components/widget.jsx
Labels: enhancement, frontend

#140 Frontend fix graphs
  .github/workflows/arduino-build.yaml
  .github/workflows/deploy.yaml
  .github/workflows/update-secrets.yaml
  docker-compose.yml
  fullstack/src/app/api/recieve-data/route.js
  fullstack/src/app/page.js
  fullstack/src/app/utils/chartUtils.js
  fullstack/src/components/cloud.jsx
  fullstack/src/components/footer.jsx
  fullstack/src/components/graphs/BarChartComponent.jsx
  fullstack/src/components/graphs/LineChartComponent.jsx
  fullstack/src/components/widget.jsx
Labels: frontend
