Repository OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa, pull requests merged in 2024-10, with the labels that each got.

#106 Update main
  .github/workflows/deploy.yaml
  docker-compose.yml
  fullstack/Dockerfile
  fullstack/components.json
  fullstack/package-lock.json
  fullstack/package.json
  fullstack/postcss.config.js
  fullstack/src/app/api/co2-data/route.js
  fullstack/src/app/api/dust-data/route.js
  fullstack/src/app/api/gas-data/route.js
  fullstack/src/app/api/humidity-data/route.js
  fullstack/src/app/api/pressure-data/route.js
  fullstack/src/app/api/recieve-data/route.js
  fullstack/src/app/api/temperature-data/route.js
  fullstack/src/app/api/wind-data/route.js
  fullstack/src/app/favicon.ico
  fullstack/src/app/globals.css
  fullstack/src/app/page.css
  fullstack/src/app/page.js
  fullstack/src/app/utils/chartUtils.js
  fullstack/src/app/utils/receive-data-helper.js
  fullstack/src/app/utils/recieve-data-helper.js
  fullstack/src/components/WidgetBase.css
  fullstack/src/components/graphs/BarChartComponent.jsx
  fullstack/src/components/graphs/LineChartComponent.jsx
  fullstack/src/components/ui/button.jsx
  fullstack/src/components/ui/card.jsx
  fullstack/src/components/ui/chart.jsx
  fullstack/src/components/widget.jsx
  fullstack/src/lib/utils.js
  fullstack/tailwind.config.js
  sensors/co2_sensor_32u4/co2_sensor_32u4.ino
  sensors/dust_sensor/dust_sensor.ino
  sensors/gas-sensor/gas-sensor.ino
  sensors/i2c_master_slave/20240909_134650.jpg
  sensors/i2c_master_slave/32u4_co2_i2c_slave/32u4_co2_i2c_slave.ino
  sensors/i2c_master_slave/Readme.md
  sensors/i2c_master_slave/mega_slave/mega_slave.ino
  sensors/i2c_master_slave/ttgo_master/ttgo_master.ino
Labels: development, database, backend

#110 Displaying live data from the api
  fullstack/README.md
  fullstack/package-lock.json
  fullstack/package.json
  fullstack/src/app/layout.js
  fullstack/src/app/page.js
  fullstack/src/app/utils/providers/ReactQueryProvider.js
  fullstack/src/components/container.jsx
  fullstack/src/components/widget.jsx
Labels: database, frontend

#115 Updated Backend
  fullstack/src/app/api/co2-data/route.js
  fullstack/src/app/api/dust-data/route.js
  fullstack/src/app/api/gas-data/route.js
  fullstack/src/app/api/get-data/route.js
  fullstack/src/app/api/humidity-data/route.js
  fullstack/src/app/api/pressure-data/route.js
  fullstack/src/app/api/recieve-data/route.js
  fullstack/src/app/api/temperature-data/route.js
  fullstack/src/app/api/wind-data/route.js
  fullstack/src/app/utils/ratelimit.js
Labels: security, backend

#120 Frontend tooltips and removals
  fullstack/package-lock.json
  fullstack/package.json
  fullstack/src/app/layout.js
  fullstack/src/app/page.js
  fullstack/src/components/Webcam/Webcam.css
  fullstack/src/components/Webcam/Webcam.jsx
  fullstack/src/components/ui/tooltip.jsx
  fullstack/src/components/widget.jsx
Labels: enhancement, frontend
